# Generated by Django 5.1.6 on 2025-05-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_alter_jobpost_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='recruiter',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='remote_available',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
